# Generated by Django 6.0.6 on 2026-07-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('tourist', 'Tourist'), ('admin', 'Administrator'), ('tourist_guide', 'Tourist Guide')], default='tourist', max_length=20),
        ),
    ]
