# Generated by Django 6.0.6 on 2026-07-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='visitor_type',
            field=models.CharField(choices=[('local', 'Local'), ('tourist', 'Tourist')], default='tourist', max_length=10),
        ),
    ]
