# Generated by Django 6.0.6 on 2026-07-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_location_customuser_visitor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
