# Generated by Django 6.0.6 on 2026-06-25 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('historical_background', models.TextField()),
                ('cultural_significance', models.TextField()),
                ('fun_fact', models.TextField(blank=True)),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QRMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_string', models.CharField(max_length=500, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bonus_creature', models.CharField(blank=True, max_length=100)),
                ('unlock_type', models.CharField(choices=[('cultural_story', 'Cultural Story'), ('ar_creature', 'AR Creature'), ('hidden_game', 'Hidden Game Content')], default='cultural_story', max_length=50)),
                ('scan_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_markers', to='qr_scan.culturalspot')),
            ],
        ),
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('choices', models.JSONField()),
                ('correct_index', models.IntegerField()),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qr_scan.culturalspot')),
            ],
        ),
        migrations.CreateModel(
            name='QRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('qr_marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='qr_scan.qrmarker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'qr_marker')},
            },
        ),
        migrations.CreateModel(
            name='SpotBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr_scan.culturalspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'spot')},
            },
        ),
    ]
