# Generated by Django 6.0.6 on 2026-06-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_scan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalspot',
            name='hook',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='culturalspot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='spot_images/'),
        ),
    ]
