# Generated by Django 6.0.6 on 2026-06-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_scan', '0004_interactivemappin_alter_triviaattempt_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalspot',
            name='feature_types',
            field=models.JSONField(default=list),
        ),
    ]
