# Generated by Django 6.0.6 on 2026-06-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_scan', '0005_culturalspot_feature_types'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InteractiveMapPin',
        ),
        migrations.AddField(
            model_name='culturalspot',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
