# Generated by Django 6.0.6 on 2026-06-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_scan', '0006_delete_interactivemappin_culturalspot_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalspot',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
