# Generated by Django 6.0.6 on 2026-06-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_scan', '0007_culturalspot_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalspot',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='spot_images/'),
        ),
        migrations.AddField(
            model_name='culturalspot',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='spot_images/'),
        ),
    ]
