# Generated by Django 6.0.6 on 2026-06-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_scan', '0008_culturalspot_image2_culturalspot_image3'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(max_length=10)),
                ('tagline', models.CharField(max_length=200)),
                ('type_name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#E91E8C', max_length=20)),
                ('about', models.TextField()),
                ('significance', models.TextField()),
                ('facts', models.JSONField(blank=True, default=list)),
                ('model_3d', models.FileField(blank=True, null=True, upload_to='models/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
