# Generated by Django 6.0.6 on 2026-06-29 11:21

import qr_scan.cloudinary_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_scan', '0009_culturalicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalicon',
            name='model_3d',
            field=models.FileField(blank=True, null=True, storage=qr_scan.cloudinary_storage.CloudinaryRawStorage(), upload_to='lakbay/models/'),
        ),
    ]
