# Generated by Django 6.0.6 on 2026-06-30 12:46

import qr_scan.cloudinary_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_scan', '0011_alter_culturalicon_model_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalspot',
            name='model_3d',
            field=models.FileField(blank=True, max_length=500, null=True, storage=qr_scan.cloudinary_storage.CloudinaryRawStorage(), upload_to='lakbay/models/'),
        ),
    ]
