# Generated by Django 6.0.6 on 2026-07-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_scan', '0013_triviaquestion_explanation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ar_targets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
