# Generated by Django 6.0.6 on 2026-07-09 03:54

import qr_scan.cloudinary_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_scan', '0014_artarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='artarget',
            name='model_3d',
            field=models.FileField(blank=True, max_length=500, null=True, storage=qr_scan.cloudinary_storage.CloudinaryRawStorage(), upload_to='lakbay/models/'),
        ),
    ]
