# Generated by Django 6.0.6 on 2026-07-09 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_scan', '0015_artarget_model_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviaquestion',
            name='ar_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qr_scan.artarget'),
        ),
    ]
