# Generated by Django 6.0.6 on 2026-08-22 14:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_scan', '0016_triviaquestion_ar_target'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artarget',
            options={'ordering': ['spot', 'slot_number', '-created_at']},
        ),
        migrations.AddField(
            model_name='artarget',
            name='hint',
            field=models.TextField(blank=True, help_text="Location hint to help users find the target (e.g. 'go to west side and find the art')"),
        ),
        migrations.AddField(
            model_name='artarget',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('mythical', 'Mythical'), ('legendary', 'Legendary')], default='common', max_length=20),
        ),
        migrations.AddField(
            model_name='artarget',
            name='slot_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='Model slot number for this building (1 to 10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='artarget',
            name='spot',
            field=models.ForeignKey(blank=True, help_text='Building or Landmark where this art is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_targets', to='qr_scan.culturalspot'),
        ),
    ]
