# Generated by Django 6.0.6 on 2026-08-22 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_scan', '0017_alter_artarget_options_artarget_hint_artarget_rarity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artarget',
            options={'ordering': ['building', 'slot_number', '-created_at']},
        ),
        migrations.AddField(
            model_name='artarget',
            name='building',
            field=models.CharField(choices=[('S1', 'Building S1'), ('S2', 'Building S2'), ('S3', 'Building S3')], default='S1', help_text='Designated Building / Structure (S1, S2, or S3)', max_length=10),
        ),
        migrations.AlterField(
            model_name='artarget',
            name='spot',
            field=models.ForeignKey(blank=True, help_text='Optional Cultural Landmark associated with this art', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_targets', to='qr_scan.culturalspot'),
        ),
    ]
