# Generated by Django 6.0.6 on 2026-08-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_scan', '0018_alter_artarget_options_artarget_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalspot',
            name='required_level',
            field=models.PositiveIntegerField(default=1, help_text='Minimum explorer level required to unlock/scan this spot'),
        ),
        migrations.AddField(
            model_name='culturalspot',
            name='xp_reward',
            field=models.PositiveIntegerField(default=50, help_text='XP awarded to user upon scanning this spot'),
        ),
    ]
