# Generated by Django 6.0.6 on 2026-09-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_scan', '0019_culturalspot_required_level_culturalspot_xp_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('tier', models.PositiveIntegerField(default=1)),
                ('min_xp', models.PositiveIntegerField(default=0)),
                ('max_xp', models.PositiveIntegerField(blank=True, null=True)),
                ('icon', models.CharField(default='compass', max_length=50)),
                ('color', models.CharField(default='#1A56DB', max_length=30)),
                ('badge_image', models.ImageField(blank=True, null=True, upload_to='milestone_badges/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tier', 'min_xp'],
            },
        ),
    ]
