# Generated by Django 6.0.6 on 2026-07-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_appsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpromotion',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpromotion',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
