# Generated by Django 6.0.6 on 2026-07-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_userpromotion_latitude_userpromotion_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpromotion',
            name='is_place',
            field=models.BooleanField(default=False),
        ),
    ]
