# Generated by Django 6.0.6 on 2026-07-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_userpromotion_is_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinbundle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bundle_coins/'),
        ),
    ]
